docker:
  - image: circleci/android:api-30
environment:
  JVM_OPTS: -Xmx1536m
  GRADLE_OPTS: '
    -Dorg.gradle.daemon=false
    -Dorg.gradle.jvmargs="-Xmx2048m
    -XX:+HeapDumpOnOutOfMemoryError"
    -Dkotlin.compiler.execution.strategy=in-process
    -Dkotlin.incremental=false
    '
