steps:
  - run:
      command: |
        curl -sL firebase.tools | bash
  - jq/install
  - run:
      name: Deploy
      command: |
        PROJECT_NAME=`echo ${CIRCLE_REPOSITORY_URL}  \
          | sed -e "s/git@github.com://" | sed -e "s/.git//"`
        echo Log::PROJECT_NAME:${PROJECT_NAME}
        RELEASE_NOTE=`curl -u ${GITHUB_PERSONAL_ACCESS_TOKEN} \
          -ks https://api.github.com/repos/${PROJECT_NAME}/commits?per_page=1  \
          | jq -r .[].commit.message`
        echo Log::RELEASE_NOTE:${RELEASE_NOTE}
        APP_ID=`cat app/src/${ENV}/google-services.json | jq -r '.client[].client_info.mobilesdk_app_id'`
        echo Log::APP_ID:${APP_ID}::RELEASE_NOTE:${RELEASE_NOTE}
        firebase appdistribution:distribute ./app/build/outputs/apk/${ENV}/release/app-${ENV}-release.apk  \
        --app ${APP_ID}  \
        --token ${FIREBASE_AUTH_TOKEN}  \
        --testers "${SLACK_RELATION_MAILADRESS}"  \
        --release-notes "${RELEASE_NOTE}"  \
